name: Node CI-CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up Node
      uses: actions/setup-node@v4
      with:
        node-version:  '20.x'
        cache: 'npm' 
    - name: Build in node
      run: |
        npm install
        npm run build
        
    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: nextjs-build
        path: ./ 


  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Ambiente
        uses: actions/setup-node@v4
        with:
          node-version:  '20.x'

      - name: Instalar dependências
        run: |
          npm ci
      - name: Rodar testes unitários
        run: |
          npx jest --ci --coverage --coverageReporters=lcov --coverageReporters=text

      - name: Upload relatório de testes
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: |
            report/
            coverage/
            
  security-scan:
    needs : tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Rodar auditoria de segurança
        run: npm audit --audit-level=moderate
