name: Node CI-CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up Node
      uses: actions/setup-node@v4
      with:
        node-version:  '20.x'
        cache: 'npm' 
    - name: Build in node
      run: |
        npm install
        npm run build
        
    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: nextjs-build
        path: ./ 


  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Ambiente
        uses: actions/setup-node@v4
        with:
          node-version:  '20.x'

      - name: Instalar dependências
        run: |
          npm ci
      - name: Rodar testes unitários
        run: |
          npx jest --ci --coverage --coverageReporters=lcov --coverageReporters=text

      - name: Upload relatório de testes
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: |
            report/
            coverage/
    docs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - name: Gerar documentação
        run: npx jsdoc -c jsdoc.json
       - name: Publicar no GitHub Pages
       - name: Instalar dependências
         run: npm ci
         uses: peaceiris/actions-gh-pages@v4
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./out
  # Devido algumas falhas serem encontradas, vamos utilizar essse JOB apos a correção das falhas       
  # security-scan:
    # needs : tests
    # runs-on: ubuntu-latest
    # steps:
    #   - name: Checkout código
    #     uses: actions/checkout@v4
      
    #   - name: Configurar Node.js
    #     uses: actions/setup-node@v4
    #     with:
    #       node-version: '20' 
    #       cache: 'npm'

    #   - name: Instalar Dependências
    #     run: npm ci

    #   - name: Rodar auditoria de segurança 
    #     run: npm audit --audit-level=moderate
